// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUkfdw3Rdi7JG5XeKgBCulEuRw5c_jZ4M',
    appId: '1:603628370602:web:5be147bc0f453be4b9aed3',
    messagingSenderId: '603628370602',
    projectId: 'diacareplus-e9eb3',
    authDomain: 'diacareplus-e9eb3.firebaseapp.com',
    storageBucket: 'diacareplus-e9eb3.firebasestorage.app',
    measurementId: 'G-Z1RS02F6XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUkfdw3Rdi7JG5XeKgBCulEuRw5c_jZ4M',
    appId: '1:603628370602:android:550de13aa48e8beeb9aed3',
    messagingSenderId: '603628370602',
    projectId: 'diacareplus-e9eb3',
    storageBucket: 'diacareplus-e9eb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUkfdw3Rdi7JG5XeKgBCulEuRw5c_jZ4M',
    // Placeholder - iOS App ID not provided
    appId: '1:603628370602:ios:placeholder', 
    messagingSenderId: '603628370602',
    projectId: 'diacareplus-e9eb3',
    storageBucket: 'diacareplus-e9eb3.firebasestorage.app',
    iosBundleId: 'com.example.flutterDiacare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUkfdw3Rdi7JG5XeKgBCulEuRw5c_jZ4M',
    // Placeholder - macOS App ID not provided
    appId: '1:603628370602:ios:placeholder', 
    messagingSenderId: '603628370602',
    projectId: 'diacareplus-e9eb3',
    storageBucket: 'diacareplus-e9eb3.firebasestorage.app',
    iosBundleId: 'com.example.flutterDiacare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUkfdw3Rdi7JG5XeKgBCulEuRw5c_jZ4M',
    appId: '1:603628370602:web:5be147bc0f453be4b9aed3', // Often uses Web App ID
    messagingSenderId: '603628370602',
    projectId: 'diacareplus-e9eb3',
    authDomain: 'diacareplus-e9eb3.firebaseapp.com',
    storageBucket: 'diacareplus-e9eb3.firebasestorage.app',
    measurementId: 'G-Z1RS02F6XN',
  );
}
