// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB51bLGyl60Z_5rGnBtm40WVxvJrUZpa10',
    appId: '1:699856000358:web:4f4b5d6e8d94f7a8cc24a7',
    messagingSenderId: '699856000358',
    projectId: 'project1-2028a',
    authDomain: 'project1-2028a.firebaseapp.com',
    storageBucket: 'project1-2028a.firebasestorage.app',
    measurementId: 'G-J3X4L8MNQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB51bLGyl60Z_5rGnBtm40WVxvJrUZpa10',
    appId: '1:699856000358:android:bab46864e58e63a7cc24a7',
    messagingSenderId: '699856000358',
    projectId: 'project1-2028a',
    storageBucket: 'project1-2028a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB51bLGyl60Z_5rGnBtm40WVxvJrUZpa10',
    appId: '1:699856000358:ios:4f4b5d6e8d94f7a8cc24a7',
    messagingSenderId: '699856000358',
    projectId: 'project1-2028a',
    storageBucket: 'project1-2028a.firebasestorage.app',
    iosBundleId: 'com.example.flutterDiacare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB51bLGyl60Z_5rGnBtm40WVxvJrUZpa10',
    appId: '1:699856000358:ios:4f4b5d6e8d94f7a8cc24a7',
    messagingSenderId: '699856000358',
    projectId: 'project1-2028a',
    storageBucket: 'project1-2028a.firebasestorage.app',
    iosBundleId: 'com.example.flutterDiacare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB51bLGyl60Z_5rGnBtm40WVxvJrUZpa10',
    appId: '1:699856000358:web:4f4b5d6e8d94f7a8cc24a7',
    messagingSenderId: '699856000358',
    projectId: 'project1-2028a',
    authDomain: 'project1-2028a.firebaseapp.com',
    storageBucket: 'project1-2028a.firebasestorage.app',
    measurementId: 'G-J3X4L8MNQR',
  );
}
